# Generated by Django 3.1 on 2020-08-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myBlog_title', models.CharField(max_length=50)),
                ('myBlog_author', models.CharField(max_length=50)),
                ('myBlog_datetime', models.DateTimeField(verbose_name='Date Published')),
                ('myBlog_content', models.TextField()),
            ],
        ),
    ]
