# Generated by Django 3.1 on 2020-08-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='id',
        ),
        migrations.AddField(
            model_name='myblog',
            name='myBlog_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
