# Generated by Django 3.1 on 2020-08-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200812_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='myBlog_author',
        ),
    ]
