# Generated by Django 3.1 on 2020-08-16 05:34

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='myBlog_content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
